name: Create PR via GitHub API

on:
  push:
    branches:
      - feature/*

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "Bryan Mena V"
          git config user.email "mena97villalobos@gmail.com"

      - name: Make your changes (optional)
        run: |
          # Example placeholder
          echo "Updated at $(date)" >> generated.txt

      - name: Commit changes if any
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: automated update from GitHub Action"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi

      - name: Create pull request using GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BASE_BRANCH: main                      # branch to merge into
          PR_TITLE: "Automated PR from GitHub Action"
          PR_BODY: |
            This pull request was created automatically by a GitHub Action.
        run: |
          # Check if PR already exists
          PR_EXISTS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/pulls?head=${REPO%%/*}:$HEAD_BRANCH&base=$BASE_BRANCH" | jq '.[0].id')

          if [ "$PR_EXISTS" != "null" ] && [ -n "$PR_EXISTS" ]; then
            echo "PR already exists: ID $PR_EXISTS"
            exit 0
          fi

          HEAD_BRANCH="${GITHUB_REF#refs/heads/}"

          curl -X POST -s \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/pulls \
            -d "$(jq -n \
              --arg title "$PR_TITLE" \
              --arg head "$HEAD_BRANCH" \
              --arg base "$BASE_BRANCH" \
              --arg body "$PR_BODY" \
              '{title: $title, head: $head, base: $base, body: $body}')"